<?php

use Illuminate\Database\Seeder;
use App\Suscriber;

class SuscribersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      foreach(Self::SUSCRIBERS as $s){
        echo "Inserting:: ".$s[0]."\n";

        if(!filter_var($s[0], FILTER_VALIDATE_EMAIL)){
          continue;
        }

        /*if(preg_match("/^\w+$/i", "Gomez")){
          dd('valido');
        }
        
        dd('find');*/


      	$exists = Suscriber::where('email', $s[0])->exists();
      	if($exists){
      		continue;
      	}
        
      	$sus = new Suscriber;
      	$sus->name = $s[1] == "" ? NULL : strtoupper($s[1]);        
      	$sus->email = $s[0];
      	if($sus->save()){
      		echo $s[0]." Saved!\n";
      	}      	
      }
    }

    const SUSCRIBERS = [
      ['Airam_lupita21@hotmail.com','Maria castro'],
['jacintatorres6365@gmail.com','jacinta'],
['gutierrezescobar84@gmail.com','Enrique'],
['elmar1801@hotmail.com','Elvira Martínez Ramírez'],
['jaquelinguadalupe1208@gmail.com','Jaqueline Guadalupe Rojas Perez'],
['sara200907@hotmail.com','sara200907@hotmail.com'],
['jhonasort678@gmail.com','jonas ortega'],
['nohemy.janet25@gmail.com','Nohemy Janet Impa Condori'],
['rstiven046@gmail.com','stiven restrepo'],
['jccgconsultores@gmail.com','Juan Carlos Castillo Gomez'],
['ggonzalez958@misena.edu.co','Gustavo González'],
['mariacarvajal39@hotmail.com','Maria carvajal'],
['yohanadesalazar@gmail.com','yohana henao'],
['ferpommier@hotmail.com','Mario Fernando Pommier Porro'],
['sai_monic@hotmail.com','Saida Tincuta'],
['guidocorani@gmail.com','Guido Apata'],
['dorcly.lindor@yahoo.com','Dorcély LINDOR'],
['zoilaecaal@hotmail.com','Zoila Esperanza Caal de Tziboy'],
['nailapilar@gmail.com','Naila Pilar Condori Oquendo'],
['cabreraherland@gmail.com','Herland'],
['giovanita.bustos@gmail.com','Giovana'],
['alexguevacri@gmail.com','Alexander Vargas'],
['rafaelcolquegarcia@gmail.com','RAFAEL COLQUE'],
['sander623@gmail.com','ING. ALEXANDER SARAVIA ANDIA'],
['j.mc2@hotmail.com','Jose'],
['ronnyomar23@gmail.com','Ronny Sena'],
['anita.intriago.vega.76@gmail.com','Anita'],
['mecotru08@gmail.com','Merly Córdoba Trujillo'],
['salmaraz164@gmail.com','Sol'],
['contabilizalo.com@gmail.com','Wilcor'],
['expertofitness@gmail.com','luz'],
['erastovand47@hotmail.com','Erasmo'],
['giovanaquispe210@gmail.com','Giovana'],
['martinezhenrydario@gmail.com','Henry martinez'],
['maritmacas65@hotmail.com','Marit'],
['limbert.z.michel@gmail.com','Limbert Zarate Michel'],
['mireyalls0811@gamil.com','elsy mireya'],
['noverm72@gmail.com','noverm72@gmail.com'],
['jeancarlossaenz9@gmail.com','Jean Carlos Saenz Fuentes'],
['deadarrow2030@gmail.com','Monica Mere'],
['kriztian150489@gmail.com','Christian Leyva'],
['linnetempena30@gmail.com','Linnet Marcelle Peña Tavárez'],
['ramses.bonilla@yahoo.es','Ramses bonilla'],
['ang.cuevas.13@gmail.com','Angela'],
['luiguilxx@gmail.com','Luis'],
['chris.sha.cc@gmail.com','Christian Chirinos Mamani'],
['guablejoseluis@gmail.com','Jose Luis'],
['noverm72@gamil.com','nover melecio'],
['sauemy2020@gamil.com','MIREYA'],
['s88roderick@gmail.com','Seil'],
['ledesmamiguel83@gmail.com','Miguel Ledesma'],
['cayubakaterine@gmail.com','Katherine cayuba cueva'],
['rivera@hotmail.com','Abraham niebles Rivera'],
['asblady@gmail.com','Blady'],
['anrango23@hotmail.com','Diana Anrango'],
['victorhugoalcobasoliz@gmail.com','Víctor Hugo Alcoba Soliz'],
['rimerniltonchoquemamani@gmail.com','Rimer Nilton Choque Mamani'],
['alexmillio94@gmail.com','Jonathan Alex Huamani Millio'],
['ronald_papi2@hotmail.com','Ronald Benavente Cornejo'],
['aymurofiesta@gmail.com','Beatriz'],
['erikagorena17@hotmail.com','Erika gorena'],
['jcfeliz@gmail.com','Juan Carlos Feliz Ramirez'],
['Ulisessixtocastaneda@gmail.com','Ulises Castañeda Gutiérrez'],
['ferpommier@hotmail.com','Mario Fernando Pommier Porro'],
['a.aleiram@gmail.com','Mariela'],
['marcelochelitoborja@gmail.com','Justo Marcelo Borja'],
['isabelsajquiy19@hotmail.com','Isabel Pérez'],
['luisantonio.agricultura@gmail.com','Luis Antonio Maldonado Maldonado'],
['lopezvillarroelmarcoantonio@gmail.com','Marco Antonio López Villarroel'],
['nestormv.85@gmail.com','Nestor mamani vino'],
['jacintatorres6365@gmail.com','jacinta'],
['marleny@culturatravelclub.com','Marleny'],
['ocastillo66@gmail.com','Orlando Castillo'],
['elibertorivera376@gmail.com','Gerson'],
['diego_castro_24@outlook.es','Diego'],
['rafaelcolquegarcia@gmail.com','RAFAEL COLQUE'],
['fabicita48352@gmail.com','fabiola medina justiniano'],
['gaby.spq1@gmail.com','Gaby Silvia Pedraza'],
['leyddymendozaoliver07032019@gmail.com','Leyddy Mendoza'],
['yanet29rios@gmail.com','Yanet'],
['juanda19941@outlook.com','JUAN CARLOS VILCHES PACHECO'],
['edgarhut_12@hotmail.com','Edgar'],
['carme.rst@gmail.com','Carmen rosa soruco tejerina'],
['beticita382@gmail.com','Beatriz Tito'],
['oscarespana2000@gmail.com','Oscar'],
['tayheros59@gmail.com','Taylor Hernandez Osorio'],
['jcmsocoser@gmail.com','CARLOS MACHICADO'],
['edson.mondaca@gmail.com','Brian'],
['nolvianluque@yahoo.es','Nlolvian Luque'],
['pereznathalia302@gmail.com','Nathalia Medina'],
['vicalalv@espol.edu.ec','Victor Alvarado'],
['hormiga141521@gmail.com','Nohemi Xolo Tominez'],
['juankiss9123@gmail.com','Juan Carlos Flores Garcia'],
['silverpay@hotmail.com','Silvestre'],
['arteagaricardo661@gmail.com','Ricardo'],
['LuimiMincholita@gmail.com','Luisa Yobani Minchola Rojas'],
['crismartpc@gmail.com','Cristóbal Ticona'],
['verajoseluis@hotmail.com','José Luis vera loor'],
['titoespinozafernando@gmail.com','Fernando'],
['oscar9000@gmail.com','√ìscar Higuera'],
['dgomezmolina@gmail.com','Doris cristina Gomez'],
['rogeliochoquehuanca1975@gmail.com','Rogelio'],
['truman.panduroyalta@gmail.com','Truman Martin Panduro Yalta'],
['velardechambiangela@gmail.com','Beatriz Angela Velarde Chambi'],
['christian234cardenas56@gmail.com','Christian Javier Cárdenas Hernández'],
['ismael14qc@gmail.com','Ismael Quino'],
['fernandoaarce1975@gmail.com','FERNANDO ADOLFO ARCE HURTADO'],
['juana.ap.co@gmail.com','Juana'],
['domenicobaez@gmail.com','Domenico'],
['js.acosta1@gmail.com','Jose'],
['madrianap7@gmail.com','Adriana'],
['shierlyzc@gmail.com','SHIERLY ZURITA COTAÑA'],
['pejancoluc@gmail.com','Pedro'],
['mariesquivel2409tejada@hotmail.com','mariela'],
['velazquezcondesonia@gmail.com','Sonia Velázquez conde'],
['danieliithalike@gmail.com','Daniela Vargas duran'],
['gonzalomarroquin629@hotmail.com','Gonzalo Marroquin'],
['myumisaca@hotmail.com','Mony'],
['haylin.rodriguez@hotmail.com','Sthefany Rodriguez'],
['wguzher81264@gmail.com','Willams'],
['mariaisabelrg@gmail.com','Maria Isabel Rodriguez G'],
['contador1359@hotmail.com','David Sanchez Ortiz'],
['maribel.zambrano19@gmail.com','Maribel Zambrano'],
['pauliplast@hotmail.com','Jahn'],
['chichi_tellez@hotmail.com','William Tellez'],
['ivan_misiones@hotmail.com','Ivan Emiliano Rogin'],
['marsal_777@hotmail.es','Mario Ernesto Salazar Balderrama'],
['alinachura726@gmail.com','Alina Mery Chura Torrez'],
['adrianaromero2489@gmail.com','Adriana Mosquera'],
['Masterencobros@gmail.com','James'],
['segoalcar1@gmail.com','Carolina Dimelsa Segovia Alvarez'],
['javierroediger15@gmail.com','Ernesto'],
['varelamonteromellvy@gmail.com','Mellvy Angelica Varela Montero'],
['cesar_pp78@hotmail.com','César Augusto Peña Pacherre'],
['mercedeslive2010@hotmail.com','Irene Mercedes Gutierrez'],
['marcialej@hotmail.com','Marcial Alejandro Castillo'],
['ericelflor@gmail.com','Eri'],
['egacdc@hotmail.com','Rene'],
['dilsong85@gmail.com','Dilson Ricardo Gonzales Alipaz'],
['alcicorrav@gmail.com','ISA Corrales'],
['renatamarina163@gmail.com','Renata'],
['g.avila51@yahoo.com','Gina Avila Cabrera'],
['augustoalma_0591@outlook.es','Eugenio Almagro C'],
['tacoovacadiliofrancisco@gmail.com','Dilio Francisco Tacoo Vaca'],
['munoz-marcia5970@unesum.edu.ec','Marcia Estefanía Muñoz Muñoz'],
['fmbanegas@gmail.com','Marcos Meza'],
['mariagabrielaandradebarba@gmail.com','MARIA GABRIELA ANDRADE BARBA'],
['agripinovargas206@gmail.com','Agripino'],
['rsan2366@hotmail.com','ROGER SANTIAGO'],
['julyale.c1108@gmail.com','July Cuello'],
['anijulielf@gmail.com','Julia Flores Lobo'],
['sandrarosas2308@gmail.com','Sandra Rosas'],
['crucy.espinoza@gmail.com','Cruz Espinoza'],
['22yotha@gmail.com','Edgar soliz'],
['trivinozzaida50@gmail.com','Zaida Janneth Triviño Garzón'],
['marco.lasso08@gmail.com','Marco Aurelio Lasso'],
['camiama48@gmail.com','Luz Vargas'],
['brislymiranda@gmail.com','BRISLY MIRANDA OROZCO'],
['marcoantoniopaton8@gmail.com','Marcó Antonio Paton Chambi'],
['johanna.salamanca.ochoa@gmail.com','Johanna Angelica Salamanca Ochoa'],
['d2lvly@gmail.com','Deysi Hilari'],
['wvrodriguez37@misena.edu.co','Wendy Vanesa Rodríguez gualtero'],
['zaida900216@gmail.com','Zaida'],
['eusogues1@gmail.com','Eunice Sotelo G'],
['albert_b21_98@hotmail.com','Albert Anthony Vásquez Flores'],
['joseluis.linarespurizaca@gmail.com','José Luis Linares Purizaca'],
['rhode_soria@hotmail.com','Lic. Rhode Soria Galvez'],
['noemigutierrezaguayo@gmail.com','Noemi'],
['lauramoralessolares@gmail.com','Laura'],
['lluscosalome@gmail.com','MARíA SALOME LLUSCO NINA'],
['jorge.contable@gmail.com','jorge'],
['jagotitan@gmail.com','Jesús Gómez'],
['fannycpongot.0103@gmail.com','Fanny'],
['rociomiranda3@hotmail.com','Rocio Miranda'],
['elsolcuzcatleco@hotmail.com','JOSE ANIBAl SEGOVIA'],
['wilidiz01@hotmail.com','william enrique diz berrio'],
['liliamgp12@gmail.com','lilian Magdalena González pinto'],
['vitrito.1970@gmail.com','Victor hugo triveño torrico'],
['felix36_rodriguez@yahoo.es','Félix'],
['yolasalgado664@gmail.com','ROSMERY YOLANDA VALLE SALGADO'],
['sandoval.mario.08@gmail.com','Mario Sandoval'],
['josuesar1722@yahoo.es','MIGUEL GOMEZ'],
['contablesjyg@gmail.com','Julio Yesid Gonzalez'],
['nicolascrenein@gmail.com','Sergio Nicolás Domínguez'],
['gilpachecoasociados@gmail.com','Yudith Gil'],
['licmariodelgado2016@gmail.com','Mario Delgado'],
['xime17linares@gmail.com','Ximena Linares Laura'],
['willbargud@gmail.com','William Barrientos'],
['leidyjmc03@gmail.com','Leidy Mendoza'],
['priscilamassiel.19@gmail.com','Priscila Massiel Romero Quispe'],
['elijohana300@gmail.com','Elijohana García Pérez'],
['facultad_contable@hotmail.com','REMY MARTíN BERNAL BARAJAS'],
['angelacosta16764@gmail.com','Angel ACista'],
['marincma@hotmail.com','ANGEL MARIN'],
['veronicamedeiroortiz@g.com','Verónica Medeyro ortiz'],
['yeimya3@gmail.com','Yeimy Aponte'],
['asbrid@gmail.com','Astrid Brigette Arias Díaz'],
['claudia_kastel@hotmail.com','claudia rico'],
['emilcen30@hotmail.com','EMILCEN ENCISO BERNAL'],
['contabilidadbogota@serviciosespecializados.co','Thalia katerin diaz ciro'],
['zbmamba@gmail.com','Haymeé Zamora'],
['elsyguibre@gmail.com','ELSY GUITY'],
['wilog001@hotmail.com','wilson gil'],
['juansocarrasgarcia1979@hotmail.com','JUAN SOCARRAS'],
['mivalen@hotmail.com','Maria Constanza Bonilla Aponte'],
['sumeso34@gmail.com','JAIME GULLOSO GARCIA'],
['rogerortiz038@gmail.com','Jose Roger Ortiz Campos'],
['jamaradiaga60@gmail.com','Jorge Alberto'],
['nandobartup@gmail.com','Nando Mercado'],
['aguillerame@hotmail.com','Guillermo'],
['robertoviverosaguilera@gmail.com','Roberto'],
['gabrielatsajuput@gmail.com','Gabriela'],
['miguellooez043@gmail.com','Miguel lopez'],
['armandomere@gmail.com','ARMANDO MEJíA REQUE'],
['j.rosales13@hotmail.com','Jimmy'],
['lurdescortez18@gmail.com','JHOAVANNA LOURDES CORTEZ MACHACA'],
['danigarmart@gmail.com','Danna García'],
['gongoragab@gmail.com','Gabriela Adriana Ramírez Góngora'],
['brayanrexar@gmail.com','Bryan Jhojann Choque Marca'],
['tgongoraalmanza@gmail.com','Tereza Góngora Almanza'],
['afunes@aventurasturisticas.com','Atilio Edgardo Funes Santos'],
['yulied.gallardo@hotmail.com','Yulied Gallardo Amaya'],
['lisse2303@gmail.com','Lisse Camarena'],
['constanza.lima03@gmail.com','Justina Lima Ignacio'],
['lufema86@gmail.com','Luis Fernando'],
['yeimyjo@hotmail.com','YEIMY CELEMIN'],
['saltarin0225@gmail.com','juan carlos molina'],
['marlitacueva14@gmail.com','MARLITA CUEVA CASTRO'],
['pomaingrid383@gmail.com','Ingrid Poma Mamani'],
['martincor12@yahoo.com','martin cordoba'],
['shirley.k126@gmail.com','Shirley K. Rengifo Llanos'],
['eddyruddyticona@gmail.com','Eddy Ruddy De La Riva Ticona'],
['taniamarcela1975@yahoo.es','Tania Quinche Mendoza'],
['mcesar855@gmail.com','Paulo Marin'],
['lui16vidal16@gmail.com','Luis Brayan Vidal Gonzales'],
['javierhiguerasfarfan@gmail.com','Javier Higueras Farfan'],
['agroariesperu@gmail.com','ISMAEL'],
['chuquimiaespinozacristian@gmail.com','CRISTIAN CHUQUIMIA ESPINOZA'],
['merlydazav@gmail.com','Merly Daza'],
['celiasoledadmorinigo@gmail.com','Celia Soledad Morinigo Ag√ºero'],
['pairumanimiguelangel@gmail.com','Miguel'],
['freddy.jc140379@gmail.com','Freddy'],
['CATABOHADA@GMAIL.COM','CATALINA RODRIGUEZ'],
['g.nieves.cruz.11@gmail.com','Guadalupe Nieves de la Cruz'],
['torrezjjt66@gmail.com','Juan José Torrez'],
['rodrigo890303@gmail.com','Pedro Rodrigo Niño Rozo'],
['jorgesolis2968@gmail.com','Jorge Solís'],
['andreinava87@gmail.com','Andrina Villar Arias'],
['grey0684@hotmail.com','Greicy'],
['zemerson110@gmail.com','Emerson Zavala Echevarria'],
['chaler01@hotmail.com','Chaler'],
['odalisg.1996@gmail.com','Odalis'],
['mariayuli@hotmail.com','Maria'],
['josel-2007@hotmail.com','JOSE LUIS FLORES'],
['joffrys80@gmail.com','Joffre Edwin Collaguazo Collaguazo'],
['luciperez280500@gmail.com','Adriana Lucía Pérez Rey'],
['juca_pozo@hotmail.com','Juan Carlos Pozo C'],
['lagar06sar@gmail.com','Alan Silvio Choque Gonzáles'],
['gutierrezescobar84@gmail.com','Enrique'],
['tatiana.medrano.miranda@gmail.com','Tatiana Yolanda Medrano Miranda'],
['zeballosmarquezteresa@gmail.com','Teresa Zeballos Marquez'],
['verastegui.marisabel@gmail.com','María'],
['fpino6775@hotmail.com','Felipe'],
['maripazlla42@gmail.com','Maria'],
['ectorlamas@gmail.com','Hector'],
['Lalagutierrezb@gmail.com','alejandra gutierrez'],
['yusefmedia28@outlook.es','Youssef'],
['wilsonamador@msn.com','Wilson Alejandro Amador Chacón'],
['luzfaj@gmail.com','Luz Marina Fajardo'],
['jhenymani@gmail.com','jheny'],
['guillermoguzmanmartinez@gmail.com','Guillermo Guzmán M.'],
['jorgesagitario30@gmail.com','Jorge Luis Mamani Gutiérrez'],
['marcotuliobustamantenavarro@gmail.com','Marco Bustamante'],
['ricardoveloz67@hotmail.com','Pablo Ricardo Veloz'],
['arlethluna213@gmail.com','Arlett Selene Tovar'],
['calidad.grumen@gmail.com','ING. RAMON MENDOZA LUNA'],
['jhojanstic94@gmail.com','Jhojan Vargas'],
['kq25699@gmail.com','Kevin quintero'],
['josheperez0@gmail.com','José Antonio Pérez'],
['ke25699@gmail.com','Kevin Quintero'],
['giseladuarte66hn@gmail.com','Gisela'],
['jennypitalindao@hotmail.com','Jenny Pita'],
['elsavelasquez1969@yahoo.com','Elsa Velásquez'],
['focrer789@gmail.com','Ernesto Flores'],
['gabrielacomina@yahoo.es','Gabriela'],
['suyanarios@gmail.com','Beatríz'],
['mayten.torres@gmail.com','MAYTEN TORRES'],
['jfernando9715@hotmail.com','Elizabeth hormiga palechor'],
['lazarosilgadoaz@gmail.com','LAZARO SILGADO'],
['elnegrolindo543@gmail.com','Santos Aníbal Ramírez Rubio'],
['Carolsthephanypinmar@gmail.com','Carol pinzón'],
['lualbertmc@hotmail.com','Luis Meneses Castro'],
['angelayugraee@gmail.com','Claudia Angela Yugra Escobar'],
['aymerasg@gmail.com','Alberto'],
['93mariafernanda@gmail.com','Maria Fernanda'],
['pahb3438@gmail.com','Pedro Hernández'],
['villalbauribesebastian01@gmail.com','Yoan Sebastian Villalba Uribe'],
['herdan3@gmail.com','Henry Danilo Az Hernández'],
['amalyg4@gmail.com','Amaly Paola Garcia Muraña'],
['eeescorcia92@gmail.com','Esther Escorcia Bolaño'],
['felixhernandez023@hotmail.com','FELIX DARIO HERNANDEZ PEREZ'],
['otero22285@gmail.com','Andres Otero'],
['xamavisa1@hotmail.com','Javier'],
['arelimartinezvazquez001@gmail.com','Areli Martínez Vázquez'],
['daysipulley@gmail.com','Daysi Pulley'],
['ppsamayoa20@yahoo.es','Juan Pablo Pur Samayoa'],
['mantillaelizabeth936@gmail.com','Elizabeth mantilla'],
['diamantes.77@hotmail.es','Luis'],
['carolabecia@gmail.com','Carol'],
['mariacarvajal39@hotmail.com','Maria carvajal'],
['sanjuanmartinezj@gmail.com','Jaime Sanjuan'],
['ciramoranp@gmail.com','Cira Morán'],
['lizek1909@gmail.com','Lizeth Molina Guzmán'],
['insanity0120@hotmail.com','Marcela Rocha'],
['pereiracaranavi74@gmail.com','Oscar'],
['paulina.uribe2008@hotmail.com','Paulina'],
['a5campano@gmail.com','Alvaro'],
['fenitamd@gmail.com','María Fernanda Martínez Durán'],
['cordovaoscarhugo@gmail.com','Oscar Hugo Urbano Córdova'],
['jenny_elisa_25@hotmail.com','Lidia Sabillon'],
['PLINIOIGLESIAS@GMAIL.COM','plinio'],
['edelaguilaos9583@gmail.com','Ery Del Aguila Oblitas'],
['ticos7581@gmail.com','Vladimir Fernando Vargas Titirico'],
['eric.martinez@cun.edu.co','eric maetinez c'],
['alejandro.mb_95@yahoo.com','Manfred Alejandro Maidana Burgos'],
['danitza.mch.28@gmail.com','Marianela Danitza Mamani Choque'],
['jondarsbeatriz@gmail.com','Martha Beatriz Dorado'],
['marcesa82@hotmail.com','MARCELA'],
['yperezagual@gmail.com','Yaira Pérez'],
['elmar1801@hotmail.com','Elvira Martínez Ramírez'],
['sharonbuitralex@gmail.com','Sharol'],
['wilmer.plaza1992@gmail.com','Wilmer José Plaza Angulo'],
['rezefi75@gmail.com','Rebeca'],
['sindyprm18@gmail.com','sindy paola ribera mejia'],
['sotalvarosoto@gmail.com','SANDRA MILENA OTALVARO SOTO'],
['lenriqueviii@gmail.com','LUIS ENRIQUE CUTA CRISTANCHO'],
['luzehernandez15@gmail.com','luz Elena Hernandez B'],
['ana.colmenares22@gmail.com','Ana Mercedes Colmenares'],
['nelormoreno@yahoo.com','NELSON MORENO'],
['andrea-mancipe97@hotmail.com','ANDREA CAROLINA MANCIPE BAR√ìN'],
['castillo06saray@gmail.com','Saray Castillo'],
['Breyner0914@gmail.com','Breyner Dayan Hernandez'],
['carmen-4093@hotmail.com','Carmen'],
['pz22eva@gmail.com','Eva'],
['saculpineda19@gmail.com','Zuly sacul'],
['albitaconta2015@hotmail.com','ALBA LUZ OLIVEROS ARDILA'],
['Opalacioscasas@gmail.com','Osias wladimir PALACIOS CASAS'],
['cruz_moralesalfonso@yahoo.es','Alfonso'],
['yoseligomez17@gmail.com','Yoseli'],
['cristidelosangeles@gmail.com','Cristina Quijada'],
['figurashi_16@hotmail.com','CAROLINA ESCOBAR ORTEGA'],
['yuranih22@gmail.com','Dirma Yurani Hernández sierra'],
['carolinapaco.t@gmail.com','CAROLINA PACO TARQUI'],
['patriciaduarte.asesora@gmail.com','Patricia Duarte'],
['dariocoronado@hotmail.com','DARIO CORONADO'],
['oscarvladimir656@gmail.com','Vladimir'],
['jaimes0108@hotmail.com','JAIME S. RODRIGUEZ NAVAS'],
['jucato16@gmail.com','Julio César Arias Tovar'],
['laah7@hotmail.com','Luis Alfonso Arango Holguin'],
['blalimurc@yahoo.com.co','BLANCA  LILIA MURCIA M'],
['luzyamilethquintanillaramos@gmail.com','Luz Yamileth Quintanilla Ramos'],
['michellemontantecruz@gmail.com','Karen michelle montante cruz'],
['agarajnj@gmail.com','Naijama Condori Oropeza'],
['ejherrerau@gmail.com','Edgardo Herrera. Urbina'],
['jossrodriguez299@gmail.com','Keylin Yoselin Rodriguez Sarmiento'],
['giovanaquispe210@gmail.com','Giovana'],
['mjsenam@hotmail.com','Hansel Senna'],
['ninaquispedalia23@gmail.com','Thalia'],
['karecervantesmr@unimagdalena.edu.co','Kare'],
['cheidyliliana@yahoo.com','heidy castellanos'],
['salustiayampara@gmail.com','Salustia yampara choque'],
['erika.alexandrang@gmail.com','Erika Nuñez'],
['karentatianabernalsanabria@gmail.com','Tatiana'],
['anismar11@hotmail.com','Alberto Nisperuza Martinez'],
['helljose.acj@gmail.com','JOS√â ANTONIO CALLA AGUILAR'],
['adrianyelicontreras2018@gmail.com','ADRIANYELI'],
['floresmsilvia@gmail.com','JOS√â ANTONIO CALLA AGUILAR'],
['gissethlorena@hotmail.com','GISETH LORENA CUCHIA'],
['alma.serpas@catolica.edu.sv','Alma Yolanda Serpas'],
['sergiogoytia1976@yahoo.com.ar','Sergio javier'],
['monicam3297801@gmail.com','Monica Marcela Montealegre Cuellar'],
['upicsa@cock.li','yury'],
['leidyvillarraga@hotmail.com','Leidy Villarraga'],
['karencita_2615@hotmail.com','Karen'],
['neilradagomez10@gmail.com','Neil Enrique Rada Gomez'],
['yslenia.peralta2015@gmail.com','Enmanuel'],
['elopez0907@gmail.com','Eladio'],
['jchavezrf@gmail.com','Juana Chávez'],
['','Jorge Giovanny Garcés Diaz'],
['pastornidia10@gmail.com','Nidia'],
['jmuril8523@hotmail.com','JUAN MURILLO'],
['diaentes@hotmail.com','Diana Puentes'],
['lissette9574@gmail.com','Lissette Rosario'],
['nataliaguapacha@gmail.com','Natalia Guapacha'],
['lauraalejandraespinosa@gmail.com','Laura Ramírez'],
['iaacuna@uniguajira.edu.co','Ivan acuña'],
['marcia.delacruz84@gmail.com','Marcia'],
['lilianacarmona429@gmail.com','Liliana Carmona'],
['catastrotapalhuaca@gmail.com','Alicia cisneros'],
['lcarlosguzman1969@gmail.com','Luís Carlos Guzman Prieto'],
['MEVALERO71@GMAIL.COM','María Valero'],
['moraleshumberto62@gmail.com','Medardo Humberto Morales Virguez'],
['rojo-proletario@hotmail.com','Ivan zamora Cristóbal'],
['catalina980132@gmail.com','catalina'],
['kvillanueva30@hotmail.com','CARMEN ROSA VILLANUEVA CHUAN'],
['mauriciocarvajalm1@gmail.com','Mauricio Carvajal'],
['kamesubla@hotmail.com','Kathia'],
['balguar87l@yahoo.com','Mabel balderrama'],
['luis_fernando_scott@hotmail.con','Luis'],
['maaje.1983@gmail.com','maribel ortiz'],
['figue10-estefy@hotmail.com','Brenda Figueroa'],
['magsuarez.2014@gmail.comm','Magnolia'],
['lorenacandela36@gmail.com','Lorena'],
['maryfaby13@hotmail.com','María faby osorio saldaña'],
['arneloz@yahoo.com','Arbid Neita López'],
['diegoromerorafael@gmail.com','Rafael Diego Romero'],
['nicanorfuertes2@gmail.com','Nicanor Fuertes Romero'],
['sastithvillegas@hotmail.com','sastithvillegas'],
['katalan15@hotmail.com','Luis Carlos Catalan Ajalla'],
['javasquezcastro1@hotmail.com','JORGE VASQUEZ'],
['ladygutierrezgomez@gmail.com','Lady Gutierrez'],
['linayherrera@hotmail.com','Lina yanett herrera'],
['victor_arias_arrue@yahoo.es','Victor Ariad'],
['contabilidad@redsolvers.com','luis rodriguez'],
['yeseni3180@gmail.com','yeseni  vianney coronel melo'],
['sandralilibarra@gmail.com','Sandra Liliana Ibarra'],
['Estefany151990@gmail.com','Estefany Torres'],
['armandoguzmant_1@hotmail.com','Armando Guzmán Tovar'],
['rosalesilvia.pro@gmail.com','Silvia del Carmen Martínez'],
['dianapdulce9@gmail.com','DIANA ARDILA'],
['machacazd03@gmail.com','Lic. DOMINGO MACHACA ZAPANA'],
['nruth.escalante@gmail.com','RUTH GOMEZ'],
['selvinxr@gmail.com','Selvin'],
['carolguerrero1024@gmail.com','Carol'],
['fhgarcia@misena.edu.co','Fabio García'],
['carlostama-163@hotmail.com','CARLOS MOSQUERA'],
['yuranis.figueroa.v@gmail.com','YURANIS FIGUEROA'],
['yohanzaza26@gmail.com','yohandrys milena ramirez zabala'],
['yoha1110@hotmail.com','JOHANA MILLAN'],
['marcoantonio943@hotmail.com','Marco Antonio'],
['KEVINYOLVIALVAREZ@GMAIL.COM','KEVIN YOLVI ALVAREZ CACERES'],
['yulissamarchavez13@hotmail.com','YULISSA'],
['jesusemiliomoralessaa@gmail.com','JESUS MORALES'],
['nohrag@gmail.com','Nohra García'],
['administrativa@infraestructuralegal.co','BLANCA NUBIA POVEDA PEREZ'],
['madasan0818@gmail.com','MARIA TERESA ARIAS'],
['jhoncontador13@gmail.com','JHON MUÑOZ'],
['patmeji.mejia@gmail.com','Patricia'],
['stheffanytoledo@hotmail.com','Stheffany Toledo'],
['yorjanisp@hotmail.com','Yorjanis Puello'],
['danielafigueroabermejo@hotmail.com','daniela figueroa bermejo'],
['jhonba11@hotmail.com','Jhonn Alexander'],
['carito.086@hotmail.com','diana agudelo'],
['yaleon78@gmail.com','Yanet León'],
['msebasc410@gmail.com','PERCI MALLMAL PALOMINO'],
['haroldlargacha890@gmail.com','Harold Manuel Largacha Riascos'],
['clmvargas.cv@gmail.com','Claudia Vargas'],
['suweb1a@gmail.com','marysol  najar'],
['erikalorena18@gmail.com','Erika Lorena q'],
['vajoel17@gmail.com','Johana'],
['nazly300208@gmail.com','Nazly Salazar'],
['mancad1803@hotmail.com','Maritza'],
['noenoe.nn56@gmail.com','Noe Jaime'],
['peterhernandez548@gmail.com','Pedro Hernández'],
['jiroblesp@gmail.com','Jorge Ivan Robles'],
['yulii.grado@gmail.com','Julissa Coronado Grado'],
['elviejotorres25@gmail.com','Leonel Torres Cruz'],
['nancyarevalo061104@hotmail.com','Nancy  Melgarejo Reina'],
['wilson84rqf@gmail.com','Wilson Quiñónez'],
['aurispavon123@gmail.com','Aurys pavon'],
['hbarja2311@gmail.com','Heydi Anel Barja Bravo'],
['rodolfocorinto@gmail.com','Rodolfo Lara Ibarra'],
['jmgonza53@hotmail.com','JESUS GONZALEZ'],
['c.ruizr8@gmail.com','carla'],
['anrocaver27@gmail.com','Andrea Rosa Castillo Vergara'],
['nflechasavella@yahoo.es','NANCY FLECHAS AVELLA'],
['javidescobar@hotmail.com','JAVID'],
['enathpadilla@gmail.com','Enath padilla'],
['olgajan21@gmail.com','Olga Lucia Jaramillo'],
['johanaro23@gmail.com','Johana Romero'],
['sandra.ramirez-b@uniminuto.edu.co','Sandra'],
['juseche36@gmail.com','Julio Useche'],
['anamagarciaadmon@gmail.com','Ana María'],
['solanllypoveda@hotmail.com','Ana Solanlly'],
['roblespenaj@gmail.com','jesus manuel robles'],
['cristina.rico521@gmail.com','Cristina Rico'],
['sandra.abril1705@gmail.com','SANDRA PATRICI ABRIL CHAUTA'],
['mary_4036@hotmail.com','MARY'],
['sbejaranopedraza@gmail.com','Samuel Bejarano Pedraza'],
['pedroneljurado2015@gmail.com','Pedro nel jurado bravo'],
['amparobeltran@laboada.com','AMPARO BELTRAN'],
['pepeabraham@gmail.com','José'],
['maria.isabel@hotmail.com','MARIA ISABEL LOPEZ'],
['laupaty47@gmail.com','OLGA PATRICIA TABARES MORALES'],
['bhmaigur@gmail.com','BYRON HELMER MAIGUAL RIASCOS'],
['elviszavalarsc@gmail.com','ROEL ELVIS ZAVALA SOTO'],
['carlosdiazhcr@gmail.com','Carlos Alberto Díaz'],
['nubiac2011@hotmail.com','nubia consuelo vasquez guzman'],
['salinaskaren231@gmail.com','Karen salinas'],
['omarsnchez@gmail.com','Omar Rodolfo Sánchez Obando'],
['nelmartinez4@hotmail.com','Nelson Martinez Rojas'],
['jolram5@hotmail.com','JOHNY LOPEZ RAMIREZ'],
['jeampiersqc@gmail.com','Jeampier Smith Quinteros Castro'],
['acosta.nidia@gmail.com','Nidia acosta'],
['eimaq07@gmail.com','Edinson Iván macias'],
['estebanmentemillonaria@gmail.com','Esteban saturnino paredes mollisaca'],
['samuel_ls15@hotmail.com','Samuel Felipe López Saavedra'],
['adrianaizaquita@hotmail.com','adriana izaquita'],
['jhina.rosales@unmsm.edu.pe','Jhina Rosales Liñan'],
['spatriciabello@gmail.com','Sonia Patricia Bello'],
['paocam68@hotmail.com','Andres Hernando'],
['mayrapati10821@hotmail.com','María Omaida Patiño sabogal'],
['delacmariae@gmail.com','Maria Dela cruz'],
['dpatricia.r18@gmail.com','Diana Patricia Rueda'],
['lucyaq@gmail.com','Lucia Quiñones'],
['rrhh.capacitate@gmail.com','Emigdio'],
['carpediem.kgn@hotmail.com','karina'],
['abelinomendez75@gmail.com','Abelino Mendez'],
['lilikell1201@hotmail.com','Kelly'],
['neslerdav@gmail.com','Nesler Obando'],
['lazoleticia25@gmail.com','Leticia Lazo Apaza'],
['camaca2005@gmail.com','carlos martinez carrascal'],
['amp.caicedo12@gmail.com','Luz Amparo Caicedo'],
['jorgeurrego@outlook.com','Jorge Suarez Urrego'],
['jarolmurillo10@gmail.com','Jarol'],
['Eloisita17.meab@gmail.com','Maria Eloisa Andrade Barba'],
['adriana.plazas@hotmail.com','adriana plazas'],
['jeimyandreamorales@gmail.com','Jeimy Andrea Morales'],
['marialuisapi123@gmail.com','Maria Luisa Perez Impa'],
['dianaorozcoe@hotmail.com','Diana Orozco Echeverry'],
['betsytorres2011@gmail.com','BETSY TORRES'],
['tavoo11624@gmail.com','Gustavo Alonso'],
['luisastellacp@gmail.com','Luisa Stella'],
['marinapaza@msn.com','Marina Guadalupe Apaza'],
['elioarroyo003@gmail.com','Eleazar arroyo'],
['anyelitasa07@gmail.com','Anyela Salzar'],
['andreamd718@gmail.com','Andrea'],
['imar1994g@gmail.com','Beimar Estrada Manrique'],
['Axelaviles178@gmail.com','Axel Acdiel Avilés Cortedano'],
['jacneryfcr@gmail.com','Jacnery Calzadilla'],
['fabiomurcia00@hotmail.com','Fabio Murcia'],
['carloskike.coral@gmail.com','Carlos'],
['eusebio-audi@hotmail.com','Eusebio Nuñez C.'],
['antonio.leon@municipiodequeretaro.gob.mx','Jose Antonio León Sanchez'],
['cesaraugustogarzon68@gmail.com','Cesar Augusto Garzon'],
['wuilmary.guedez@gmail.com','Wuilmary  Guedez'],
['abadaugusto@gmail.com','Augusto.Abad'],
['carlos.florez.o98@gmail.com','Carlos Florez Ospino'],
['marypao.27.10.95@gmail.com','Maria Mamani'],
['Rodrigo.al99@gmail.com','Rodrigo Andrés Lara'],
['veronica270183@gmail.com','Verónica Isabel Bejarano Ibarra'],
['apilarb1066@gmail.com','Ana del Pilar'],
['liceth0706acosta@gmail.com','Johanna Acosta Torres'],
['j.diegodaca@gmail.com','Juan Diego Campo Villa'],
['clau2563@hotmail.com','CLAUDIA PATRICIA MARTINEZ GOMEZ'],
['lelioacero@hotmail.com','EDUARDO'],
['lujo31420@gmail.com','LUIS JOSE MEJIA LEAL'],
['alejawendy@hotmail.com','Wendy Alejandra Rodríguez González'],
['carlosm.llanosuarez@hotmail.com','carlos mario llanos suarez'],
['esperanzarivase@gmail.com','Esperanza Rivas Escobar'],
['arturo.bejarano@hotmail.com','Arturo Bejarano Ibarra'],
['marcelalopezg12@gmail.com','Diana Marcela López García'],
['Sertog29@gmail.com','Sergio Hernan torres'],
['leonardorodriguezperez@hotmail.com','EDISSON'],
['pisoloto09@yahoo.com','Piedad Londoño'],
['jennybarrera2@hotmail.com','Jenny barrera'],
['Sandrita.neiva@hmail.com','Sandra Guzman'],
['itzelgarcia280999@gmail.com','Itzel martinez'],
['johansanabriacanisales@hotmail.com','JOHAN STIVEN SANABRIA CANIZALEZ'],
['MNXIMENA80@GMAIL.COM','XIMENA'],
['ykp.ramos@gmail.com','Yessica'],
['ggarciag2014@gmail.com','GLADYS GARCIA'],
['rafantmor@gmail.com','Rafael Morales'],
['jackeline.galeano67@gmail.com','JACKELINE GALEANO'],
['duvierfelipehorta123@gmail.com','Felipe Horta'],
['Yeisoncaicedo1994@gmail.com','Yeizon caicedo'],
['rebecamarcasmallma@gmail.com','Rebeca Marcas Mallma'],
['peraltacarranzaleidy@gmail.com','Leidy peralta'],
['mireyabrv97@gmail.com','Mireya Bravo Olivo'],
['orlando04paletas@gmail.com','Orlando Palechor Piñacue'],
['amoreyrac@gmail.com','Jaime Arturo Moreyra Carbajal'],
['marytorreshv@gmail.com','Maribel Torres'],
['naslyuribemira@gmail.com','Azucena'],
['joseluiscaitychivaco@gmail.com','Jose Luis'],
['juliethmartinezmerino25@gmail.com','julieth vanessa martinez meriño'],
['vertizrojascesar@gmail.com','cesar vertiz rojas'],
['johnninferm10@gmail.com','Johnninfer Moreno Martin'],
['paogarzia9@gmail.com','PAOLA GARCIA'],
['alfopaxim@gmail.com','Alfonso Paxi pocoma'],
['info@gomezzayas.com','OMAR GOMEZ ZAYAS'],
['leydijohannamorales@gmail.com','LEYDI JOHANNA MORALES MEDINA'],
['ludaro7@gmail.com','LUZ DARY ROJAS BARCO'],
['evelynlozano8@hotmail.com','Evelyn'],
['carlosss._@hotmail.com','Torres Vazquez Carlos Daniel'],
['kikopyp@gmail.com','Luis leon'],
['belkis.escobarbelkis@gmail.com','Belkis Escobar'],
['naudy2005@yahoo.es','NAUDITH GARAVITO CALDERA'],
['noraislia@gmail.com','Nora Islia Correa Silva'],
['manuel_rc1993@hotmail.com','Josué Manuel Reyes Castro'],
['diana-k-aro@hotmail.com','Diana carolina perez romero'],
['scastanoramirez@gmail.com','Sandra Milena Castaño Ramírez'],
['moralesmayra2009@hotmail.com','MAYRA ALEJANDRA MORALES SALAZAR'],
['yenypaez@hotmail.com','Jeny alexandra paez tellez'],
['dn54048@gmail.com','Edwin Daniel Navarro Mancilla'],
['ejam_consultorias@yahoo.com','EVER JAFET AHUMADA MUÑOZ'],
['Kelia_Pardo@hotmail.com','Alejandra'],
['magperez1961@gmail.com','Magdalena  Perez'],
['renecabrera3791@gmail.com','Rene Cabrera'],
['janierbecerra@gmail.com','Janier Fernando anturi Becerra'],
['julianska69@gmail.com','julian stiven sandoval orduz'],
['katherinetiria_97@yahoo.com','Catherine Tiria'],
['juanabogado2005@yahoo.com','Juan patiño'],
['Mjpinto_197@hotmail.com','María jose'],
['Maidacerpa78@gmail.com','Maida cerpa'],
['armellafaud.27@gmail.com','ANGELITO FAUD ARMELLA IVARRA'],
['cesarmilchercasas@gmail.com','Cesar'],
['moises.enamorado@gmail.com','Moises Alejandro Enamorado'],
['wverlando@gmail.com','Wverlando'],
['lucreciamamanihuanca@gmail.com','Lucrecia Raimunda Mamani Huanca'],
['jhasang12@gmail.com','Jhaneth Sandy Galarza Padilla'],
['samileya@hotmail.com','Milena amaya'],
['cardenaschalo@gmail.com','Gonzalo'],
['miguelbarros2416@gmail.com','Miguel Barros'],
['jacquelinemgonza01@gmail.com','Jacqueline medrano'],
['solucioncontable.sos@gmail.com','Stella Osorio'],
['stephanima3162@gmail.com','Stephanie'],
['torrezrivero@gmail.com','Franco Nino Torrez Rivero'],
['elkcortes@gmail.com','ELKIN'],
['mariaideliz85@gmail.com','Maria ideliz arrambide Huaman'],
['matildecarrillo1@gmail.com','Matilde Carrillo'],
['avlp2097@gmail.com','Angie Vanesa Lopez Valencia'],
['larahidlgoleonardo2002@gmail.com','Diego Leonardo Lara Hidalgo'],
['Yubisay554@gmail.com','Yubisay'],
['franky13206@gmail.com','Francisco A Ramos'],
['leo.rojas_18@hotmail.com','LEONARDO ROJAS BORDA'],
['neycimont@gmail.com','Neicy Montaño Valdivia'],
['joelbenghitumen@gmail.com','Joel Benjamín Escalera De La Tapia'],
['aquitorres@gmail.com','Gregorio'],
['angieceballos0308@gmail.com','Angie Dayanna Ceballos'],
['Dxgm17@gmail.com','Diana Ximena Gallego Marin'],
['dianita.azuara@gmail.com','Diana azuara'],
['alexlovejanny@gmail.com','Yhanet Alvarez'],
['nancifu10@gmail.com','Nancy Cifuentes C.'],
['yesmarceb@gmail.com','YENNY BENJUMEA'],
['marthaluzbc@gmail.com','Malú'],
['rogermaklein@gmail.com','Ma. Jaqueline Cuestas A.'],
['yorlyssuarez82@gmail.com','Yorlys suarez'],
['guzmanmatias964@gmail.com','GUZMAN MATIAS AMBROCIO'],
['javih1970@gmail.com','Javier Hilarion Huanca Chavez'],
['quindeyomayra.97@gmail.com','Yadira Quinde Borbor'],
['ana.colmares22@gmail.com','Ana Colmenares'],
['wagneracosta30@gmail.com','Wagner'],
['roserocordoba1995@gmail.com','Silvio Armando Rosero'],
['mabelerg7@gmail.com','Eliana Reyes'],
['sivy_24@hotmail.com','Sivy'],
['erikag160994@gmail.com','Erika Guatemal'],
['Alejandra050908@gmail.com','Alejandra Arango'],
['martamoskera@gmail.com','Martha Mosquera  Mateus'],
['merapincayjl@gmail.com','Jose pincay'],
['ssamideos@gmail.com','Sandra Milena Delgado'],
['jesus.ardilab08@gmail.com','Jesús David Ardila'],
['luzmrh2711@gmail.com','Luz marina rodriguez'],
['moniqa.8a@gmail.com','Mónica Cecilia Ochoa Muñeton'],
['markos1953@hotmail.com','MARCO ANTONIO ENCISO'],
['elvis-1506@hotmail.com','Elvis'],
['emiliomanuelleyba08@gmail.com','Emilio Leyba'],
['bettowen5492@gmail.com','Alexander'],
['csmazo@yahoo.es','Claudia'],
['momamonestier@hotmail.com','Norma'],
['soniazulemapoma@gmail.com','Sonia Zulema Poma Mamani'],
['hernandezmarin1993@hotmail.es','MIGUEL ANGEL'],
['orielysalas@gmail.com','Oriely salas'],
['rossy.benitez7@gmail.com','Adriana'],
['Yychavez3@misena.edu.co','Yajaira'],
['castrilloeliceth@gmail.com','Eliceth Castrillo'],
['wellmersh@gmail.com','Walter Romero'],
['anitapm2607@gmail.com','Ana María padilla Masabi'],
['mlvsmls@gmail.com','Liliana Valenzuela soto'],
['ubaldolu@hotmail.com','Ubaldo'],
['fredybarreda1@gmail.com','Fredy barreda alvarez'],
['Davidbi18@hotmail.com','David andrés leon lizarazo'],
['cayaloporfidio@gmail.com','Porfidio Cayalo Machado'],
['hcarrerob@gmail.com','Heidy Carrero'],
['jaime_arturo_luna@yahoo.com','Jaime luna'],
['fpaulocochi@gmail.com','Francisco Paulo Cochi'],
['choquecruzelizabeth1998@gmail.com','MARIA ELIZABETH CHOQUE CRUZ'],
['ymperez@unicauca.edu.co','Yaneth'],
['aliscairmj@gmail.com','Aliscair Enrique'],
['hruizpersonal@gmail.com','José Helmer Ruiz'],
['luism1010@gmail.com','Luis'],
['lozaantonio022@gmail.com','Antonio'],
['cleme26@gmail.com','Clemencia Araujo'],
['piloiterrazaskarina@gmail.com','Karina piloi'],
['alfonsito1542@gmail.com','Nestor'],
['amp_2112@hotmail.com','ANA MILENA PAREDES CASTELLANOS'],
['josezalez@gmail.com','José González Marcano'],
['carmenrosamejias@gmail.com','Carmen Mejias'],
['jomolina2760@protonmail.com','Jose A. Rodriguez M.'],
['oscar72322418@gmail.com','Oscar oczachoque'],
['gutierreznaglesdm@gmail.com','Dayanire Gutiérrez Nagles'],
['edgar.alconq@gmail.com','Edgar'],
['louma.25.ortegas.los@gmail.com','Lourdes María Ortega Solórzano'],
['sunegocioalderecho@gmail.com','Mauricio González'],
['wicercor@gmail.com','William Cerquera Cortés'],
['sjas2005@gmail.com','Silvia Arrivillaga'],
['yerlis.mercadov@gmail.com','Yerlys Esther Mercado Velandia'],
['cristina_armengold@hotmail.com','María Cristina'],
['margarethduqueu1990@gmail.com','Margareth Duque'],
['andreaplata1977@gmail.com','Jennifer Cardenas'],
['paulocgomez@hotmail.com','paulo gomez'],
['jeffcontabilidadgabriela@gmail.com','Jefferson Guevara Nuñez'],
['nailism.p@gmail.com','Naila Tatiana muñoz Pérez'],
['ladiosajessica@hotmail.com','Jessica'],
['johanna_alejita@hotmail.com','Johanna Tipanguano'],
['prudevela1@gmail.com','Prudencio vela ali'],
['olguiux46@gmail.com','Olga Pérez Díaz'],
['ivanribar77@gmail.com','Ivan Arturo Riveros Barrientos'],
['mar-munoz76@hotmail.com','Maricela Muñoz'],
['cocapachom@gmail.com','Maria Esther Coca Pacho'],
['mmmaiu.rt@gmail.com','Richard Rios Vasquez'],
['mdebarraza1@gmail.com','Miriam de barraza'],
['walterla23@hotmail.com','Walter'],
['Limaicamedina@mail.com','Jose carlos Limaica  Medina'],
['herreravalentina425@gmail.com','Valentina Herrera'],
['chechegiovi@gmail.com','Giovanni Vásquez Aramayo'],
['crispincoro34@gmail.com','CRISPIN CORO GUARACHI'],
['joseluis7611r@gmail.com','Jose Luis Renteria'],
['alarconvladimir30@gmail.com','VLADIMIR ALARCON RAMOS'],
['jimenezdeveloper@gmail.com','Norbert Gonzalo Jiménez Flores'],
['silst7754@gmail.com','Silvia'],
['samuelpineda62@hotmail.com','Samuel Pineda'],
['ma0657032018@unab.edu.sv','Damiana'],
['dayler121db@gmail.com','Dayler Ramos Aramayo'],
['alexandermareno15@gmail.com','Alexander Jhamil Mareño Salvatierra'],
['am061890@gmail.com','√Ålvaro'],
['ahikelarguello@gmail.com','Angela Ahikel Arguello Guerrero'],
['jcusi770@gmail.com','Juan Carlos'],
['linda6cat@gmail.com','Carla Yohana León Cabrera'],
['rnuezchavez@yahoo.com','Rafael nuñez chavez'],
['nelsonrs3027@yahoo.com','Nelson Rodríguez'],
['PAO-ANDRE-11@HOTMAIL.COM','Paola Teran'],
['eybd27@hotmail.com','Elsa Yamile'],
['dignamarielamontoyaacosta@gmail.com','Digna'],
['danicha0503@gmail.com','Elvia'],
['oscar_antonioc@hotmail.com','Oscar Antonio Coca Urbano'],
['ropagus1@gmail.com','Gustavo Rodríguez'],
['andreamerino2012@gmail.com','Andrea'],
['s.melo@msn.com','SANDRA PATRICIA MELO'],
['gabrieldrouet8@gmail.com','Gabriel Drouet'],
['nines0402@gmail.com','María Inés Penagos'],
['lilif_82@hotmail.com','Lilian Astrid Fandiño'],
['henrypatinohp@gmail.com','Henry Patiño'],
['adrianalu099@hotmail.com','Adriana Castañeda'],
['kaliireyes1996@gmail.com','Carlos  reyes'],
['jm822606@gmail.com','José Manuel Gotera Rodriguez'],
['daisyquintero2001@gmail.com','Daisy'],
['infomedicc@gmail.com','luz'],
['joselbisg@gmail.com','Joselbis'],
['zharick69200425@gmail.com','Zharick'],
['andriu.val155@gmail.com','andres felipe valencia'],
['erortegal@hotmail.com','eduardo ortega lopez'],
['josedavidfm968@gmail.com','Jose David'],
['santosarcangel64@gmail.com','Jesús Alberto Daza Ramírez'],
['hugodpm48@gmail.com','hugo'],
['olivosm86@gmail.com','Yarit'],
['claudia.roman@outlook.com','Claudia Román'],
['angel1201_01@hotmail.com','ANGELA MARIA AVILA AVILES'],
['francytp@hotmail.com','franncy tunubala'],
['eduardo.enriquez.g@gmail.com','Eduardo M. Enríquez G.'],
['nidiaaul@gmail.com','Nidia Ulchur'],
['scorrpio_0909@hotmail.com','SEGUNDO CESAR OSWALDO RODRIGUEZ RUBIO'],
['pepoerazo@gmail.com','José'],
['yulimotta1994@gmail.com','July Marcela Motta Angarita'],
['gabicha.c@gmail.com','Ana Gabriela Cevallos Castanieda'],
['m0308mendoza@gmail.com','Martha Mireya Mendoza'],
['lizeth14morales@gmail.com','Lizeth'],
['ecveduardo@hotmail.com','Eduardo castañeda'],
['randolfph04262014@gmail.com','Randol Morales'],
['a.2.maruja@gmail.com','Maruja'],
['efritagor@hotmail.com','Efrain'],
['Gibarrueto@hotmail.com','Gloria'],
['yirima012@hotmail.com','MAYIRIS'],
['caroolina1012@gmail.com','Carolina perez'],
['ricardo.dif@gmail.com','Ricardo Díaz Franco'],
['nayo47@live.com.mx','Genayo Garcia'],
['macosta20120@gmail.com','Maritza'],
['acr.7.21.09@gmail.com','Armando Conde Rodríguez'],
['contalfa@hotmail.com','Luis Fernando Agudelo Ocampo'],
['jstefagy@gmail.com','Johanna Guaña'],
['jdavid12@hotmail.com','Juan David'],
['sebasmore23@gmail.com','Sebastian Moreno Lozano'],
['fanthonspace@gmail.com','Jorge Luis Carrasco Luque'],
['gerbaco@gmail.com','Germán Eduardo'],
['ryaniquez@hotmail.com','RONALD'],
['rocio10cortes@yahoo.com','Olga cortes prieto'],
['daniylo@gmail.com','Danny'],
['linsismat@gmail.com','Ramiro'],
['mcedgar@outlook.es','Edgar Morales'],
['adrianaore3445@gmail.com','Adriana Lucia Orejuela Cortes'],
['jesusamayacardona@gmail.com','Jesus'],
['dairobarrientos@gmail.com','Dairo Barrientos'],
['samibeva9@hotmail.com','Sandra Bernal'],
['diegoalvaropaucara@gmail.com','Diego'],
['jbarreramazo@yahoo.com','Johnny Barrera'],
['karenmollo600@gmail.com','Karen Mollo'],
['michellerbn98@gmail.com','Mishelle'],
['angellisarmientoochoa@gmail.com','Angelli Sarmiento'],
['lizethalvarezbtr@gmail.com','Lizeth Graciela Alvarez Torrez'],
['kerlybarzola2001@gmail.com','Kerly'],
['Jorgeynorela@gmail.com','Jorge Luis Monterrosa'],
['robertquis21@gmail.com','Roberto Quispe Huaycho'],
['arielr0591@gmail.com','Ariel Ramos'],
['eugeniorojas53@gmail.com','Eugenio'],
['andreasanchez643@gmail.com','Andrea Sánchez Ramírez'],
['fleitasdeysi030@gmail.com','Deysi Carolina Fleitas Franco'],
['estudiosjhonsteven@gmail.com','Jhon Steven Jaramillo Becerra'],
['jota.dirtya.ra@gmail.com','Lopez Condori Jhoel Tadeo'],
['vicente12172@live.com','Vicente Quinteros'],
['andresc42137@gmail.com','Marcos'],
['risamarlopez@gmail.com','Regina Isamar Gaitan López'],
['cahzapata@gmail.com','Carlos Humberto Zapata Cano'],
['wilico-lc-90@hotmail.com','WILLAN  LIÑEIRO CORONADO'],
['sharmelym.vilca@gmail.com','Sharmely'],
['gaitanlopezsandraliseth@gmail.com','Sandra Liseth Gaitan Lopez'],
['carlosbejarano29014@gmail.com','Carlos Bejarano V.'],
['vcevallo@hotmail.com','Victor Cevallos'],
['nancygregorio909@gmail.com','Nancy'],
['cruzquispemiriam@gmail.com','Miriam Cruz Quispe'],
['richard.ingsistemas@gmail.com','Richard Daniel Pachari Rodriguez'],
['miguerojas70@hotmail.com','Miguel'],
['aramiscarcamo614@gmail.com','Aramis Nathael Ramos Cárcamo'],
['brigitt.ahime@gmail.com','ARACELI BRIGIDA CALLE QUISPE'],
['dar.fabian07@gmail.com','Darwin'],
['mjvallea@hotmail.com','Manuel valle'],
['sandrag81@yahoo.es','Sandra'],
['elinosan31@hotmail.com','Elixandre Noriega'],
['franjack25@gmail.com','Francis'],
['saosa90@hotmail.com','Omar Andrés Salazar perez'],
['jimato8111@gmail.com','Jissel'],
['pcdamian@gmail.com','Carlos damian'],
['mhrafa_18@hotmail.com','Rafael Milanes'],
['gina-0809@hotmail.com','Gina panchano'],
['marino134mm@gmail.com','Marino'],
['jmchampa25@gmail.com','José']
  ];
}